version: '3'

services:
  web:
    container_name: golastic_web
    build: .
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SERVER_PORT
    networks:
      - golastic
    ports:
      - 9999:9999

  elasticsearch:
    container_name: golastic_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment: 
      "discovery.type": "single-node"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 5s
        timeout: 5s
        retries: 12
    networks:
      - golastic
    ports:
      - 9200:9200
      - 9300:9300
    restart: always

  kibana:
    container_name: golastic_kibana
    image: docker.elastic.co/kibana/kibana:7.13.2
    depends_on: 
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS
    ports:
      - 5601:5601
    networks: 
      - golastic
    restart: always

networks:
  golastic:
    driver: bridge
